"""Build comprehensive emotion text corpus (400+ sentences)"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from src.preprocess import TextPreprocessor
from src.config import DATA_DIR

emotion_texts = {
    'happy': [
        "i am so happy today everything is wonderful",
        "this is the best day of my life i am overjoyed",
        "i feel fantastic and full of energy",
        "my heart is bursting with happiness",
        "i am absolutely thrilled beyond words",
        "what a beautiful day i feel so alive",
        "i cannot stop smiling this is incredible",
        "life is beautiful and i am so grateful",
        "i am so excited i can barely contain myself",
        "this moment is pure bliss and perfection",
        "i feel like the luckiest person in the world",
        "everything is going so well i am ecstatic",
        "i am beaming with joy and happiness",
        "this news made my entire week amazing",
        "i feel so content and at peace with everything",
        "what an amazing experience i loved every second",
        "my spirits are soaring high today",
        "i am filled with hope and positivity",
        "this is truly a dream come true for me",
        "i feel so loved and appreciated right now",
        "celebrating this wonderful achievement with joy",
        "i am delighted by how things turned out",
        "feeling grateful for all the good things in life",
        "this success fills me with pride and happiness",
        "i woke up feeling refreshed and optimistic",
        "surrounded by people i love makes me so happy",
        "the joy i feel right now is indescribable",
        "i am genuinely happy and at peace with myself",
        "what a delightful surprise this turned out to be",
        "i feel warm and fuzzy inside from happiness",
        "every little thing seems to be going right today",
        "my heart is full of gratitude and joy",
        "i am having the time of my life right now",
        "this achievement means the world to me",
        "i feel so uplifted and inspired today",
        "nothing can bring down my mood right now",
        "the happiness i feel is radiating from within",
        "i am truly enjoying every moment of this",
        "what a blessing this wonderful experience has been",
        "i feel lighthearted and carefree today",
        "laughing with my friends is the best feeling ever",
        "i am looking forward to a bright future ahead",
        "this vacation was the happiest time of my life",
        "i feel like dancing with pure happiness",
        "my family brings me so much joy every day",
        "i am so proud of what we accomplished together",
        "feeling blessed beyond measure right now",
        "the laughter and smiles are contagious today",
        "i cherish these happy moments so deeply",
        "every day feels like a gift when i am this happy",
        "my happiness knows no bounds today",
        "the world seems brighter when i am this happy",
        "i feel a deep sense of satisfaction and joy",
        "what a perfect ending to a perfect day",
        "i am radiating positivity and happiness",
        "my heart is dancing with pure delight",
        "i feel so alive and vibrant right now",
        "this serendipitous encounter made my entire day",
        "everything feels magical and wonderful today",
        "i am basking in the warmth of happiness",
        "my soul is singing with contentment and peace",
        "i am elated by the wonderful news i received",
        "this triumph deserves a joyful celebration",
        "i feel like i am walking on sunshine",
        "this pleasant surprise completely brightened my mood",
        "i am reveling in this moment of pure joy",
        "my heart swells with happiness when i think about it",
        "i am overwhelmed with positive emotions right now",
        "i feel a profound sense of well-being today",
        "my enthusiasm for life has never been greater",
    ],
    'sad': [
        "i feel so sad and lonely right now",
        "my heart is breaking into a million pieces",
        "tears keep falling and i cannot stop them",
        "i have never felt this miserable before",
        "a deep sorrow has taken over my entire being",
        "i feel empty inside like nothing matters anymore",
        "the pain in my heart is unbearable today",
        "i just want to curl up and cry forever",
        "everything feels hopeless and meaningless right now",
        "i miss the people i have lost so deeply",
        "this grief is consuming me from the inside",
        "i cannot find any joy in anything anymore",
        "my soul feels heavy with sadness",
        "i am drowning in my own tears",
        "the world seems gray and lifeless without them",
        "i feel completely defeated and broken",
        "no matter what i do the sadness follows me",
        "my heart aches with an indescribable pain",
        "i have lost all motivation and hope",
        "the loneliness is overwhelming and crushing",
        "i feel abandoned and forgotten by everyone",
        "every night i cry myself to sleep",
        "this deep melancholy will not leave me alone",
        "i feel so helpless and powerless against this sadness",
        "the weight of sorrow is crushing my spirit",
        "nothing can fill this void inside my heart",
        "i am haunted by memories of happier times",
        "this profound sadness has become my constant companion",
        "i feel invisible and unimportant to the world",
        "my heart is heavy with unspoken grief",
        "the tears come unexpectedly throughout the day",
        "i feel like a shadow of my former self",
        "this heartache is more than i can bear",
        "i am trapped in this cycle of despair",
        "the sadness sits in my chest like a stone",
        "i mourn for what could have been",
        "every happy memory now brings only pain",
        "i feel disconnected from everything and everyone",
        "this sorrow runs deeper than anyone can see",
        "i am exhausted from pretending to be okay",
        "the grief hits me in waves throughout the day",
        "i long for the past when things were better",
        "my spirit feels completely crushed and broken",
        "this sadness has become a part of who i am",
        "i cannot remember the last time i truly smiled",
        "the pain of loss never really goes away",
        "i feel so fragile and vulnerable right now",
        "every little thing reminds me of what i lost",
        "this emotional pain is physically exhausting",
        "i am numb to everything except the sadness",
        "tears well up in my eyes at the slightest thought",
        "i feel like i am grieving for my own life",
        "the melancholy envelops me like a dark cloud",
        "my heart feels like it is made of lead",
        "i am weary from carrying this emotional burden",
        "this profound sense of loss overwhelms me",
        "i feel utterly devastated by recent events",
        "the sorrow i feel is beyond words to describe",
        "i miss the warmth of their presence so desperately",
        "this sadness colors everything in shades of blue",
    ],
    'angry': [
        "i am absolutely furious right now",
        "this makes me so angry i could explode",
        "how dare you treat me like this",
        "i have never been this enraged in my life",
        "the frustration is boiling inside of me",
        "i am so fed up with all of this nonsense",
        "this injustice makes my blood boil",
        "i cannot tolerate this disrespect any longer",
        "the rage i feel is consuming me completely",
        "i am seething with anger and resentment",
        "this is completely unacceptable and outrageous",
        "i want to scream at the top of my lungs",
        "every fiber of my being is filled with fury",
        "i am so irritated i cannot think straight",
        "this blatant unfairness is driving me insane",
        "my patience has reached its absolute limit",
        "i am burning with righteous indignation",
        "the nerve of some people is unbelievable",
        "i feel like punching something right now",
        "this constant aggravation is too much to bear",
        "i am utterly disgusted by this behavior",
        "my temper is about to erupt like a volcano",
        "this is the last straw i cannot take anymore",
        "i am filled with barely contained wrath",
        "the sheer audacity makes me livid with rage",
        "i have never felt such intense animosity before",
        "this provocation is beyond anything i can handle",
        "my fury is justified and completely valid",
        "i am so angry my hands are literally shaking",
        "this mistreatment will not go unanswered",
        "i feel deeply offended and insulted by this",
        "the indignation i feel is overwhelming",
        "i am at my breaking point with this situation",
        "this betrayal has filled me with unbridled rage",
        "i am incensed by this blatant disregard",
        "my irritation has turned into full blown anger",
        "i cannot stand being treated this way anymore",
        "this outrage is completely justified and warranted",
        "i am bristling with anger and frustration",
        "the unfairness of it all makes me so mad",
        "i am about to lose my temper completely",
        "this disrespectful behavior will not be tolerated",
        "my blood pressure is rising from sheer anger",
        "i am so annoyed i could just scream out loud",
        "this provocation has pushed me over the edge",
        "i feel a burning rage deep inside my chest",
        "the gall of that person is absolutely infuriating",
        "i am simmering with barely contained fury",
        "this injustice strikes a nerve deep within me",
        "i am completely exasperated by this situation",
        "the resentment i feel is growing by the minute",
        "i am outraged by this flagrant violation of trust",
        "this hostility is a direct result of their actions",
        "i am absolutely livid about what transpired",
        "my wrath is building up like a pressure cooker",
        "this contemptible act deserves harsh consequences",
        "i am fuming with rage and cannot calm down",
        "the audacity of this provocation astounds me",
        "i am bristling with barely suppressed anger",
        "this tyrannical behavior will not stand",
    ],
    'fearful': [
        "i am absolutely terrified right now",
        "something terrible is about to happen i can feel it",
        "my heart is racing with pure fear",
        "i am shaking with fright and cannot stop",
        "please do not hurt me i am so scared",
        "the fear is paralyzing i cannot move",
        "i have never been this frightened in my life",
        "a chill of terror runs down my spine",
        "i am petrified of what might come next",
        "the anxiety is consuming every part of me",
        "i feel so unsafe and vulnerable right now",
        "my worst nightmare is coming true",
        "i am trembling with fear and dread",
        "the panic is rising and i cannot breathe",
        "i am haunted by this overwhelming sense of doom",
        "every shadow makes me jump in terror",
        "i feel trapped and there is no way out",
        "the fear has taken complete control of me",
        "i am dreading what tomorrow might bring",
        "something sinister lurks in the darkness",
        "my hands are clammy and my pulse is racing",
        "i am frozen in place by sheer terror",
        "this impending danger fills me with dread",
        "i am terrified of losing everything i love",
        "the fear grips my heart like a cold hand",
        "i cannot escape this feeling of impending doom",
        "every noise in the dark terrifies me",
        "i am petrified beyond rational thought",
        "this anxiety attack is completely overwhelming",
        "i feel hunted and completely exposed",
        "a wave of panic washes over me suddenly",
        "my worst fears are becoming reality",
        "i am besieged by terrifying thoughts",
        "the horror of this situation is indescribable",
        "i feel like prey being stalked by a predator",
        "this mortal terror has me completely paralyzed",
        "i am scared to even close my eyes at night",
        "the fear is so intense i feel physically ill",
        "i am petrified of the unknown that lies ahead",
        "this dread has settled deep into my bones",
        "i recoil in horror at what i just witnessed",
        "the darkness feels alive with unseen threats",
        "i am terror stricken and cannot think clearly",
        "my adrenaline is surging from pure fear",
        "i feel an ominous presence watching me",
        "this spine chilling sensation will not go away",
        "i am gripped by an irrational but intense fear",
        "the nightmare continues even when i am awake",
        "i am horrified by the turn of events",
        "a sense of foreboding hangs heavy in the air",
        "i feel utterly defenseless against this threat",
        "the terror has robbed me of my voice",
        "i am consumed by catastrophic thoughts",
        "this abject fear is the worst i have ever felt",
        "i cannot shake this feeling of imminent catastrophe",
        "every creak and whisper fills me with dread",
        "i am paralyzed by this overwhelming anxiety",
        "the menace i sense is all around me",
        "i feel a cold sweat from the sheer terror",
        "my breathing is shallow from the panic",
    ],
    'disgust': [
        "that is absolutely disgusting and revolting",
        "the smell makes me want to vomit",
        "i have never seen anything so repulsive",
        "this is utterly vile and nauseating",
        "the sight of it makes my stomach turn",
        "i am completely disgusted by this filth",
        "that is the most revolting thing ever",
        "i feel sick just looking at this mess",
        "the rotten stench is unbearable",
        "this is so gross i cannot even look",
        "what a foul and disgusting creature",
        "i am physically repulsed by this horror",
        "the mold and decay are utterly sickening",
        "i recoil in disgust at the mere thought",
        "this abomination should not exist",
        "the putrid odor fills me with revulsion",
        "i am nauseated by this appalling sight",
        "that food was absolutely nasty and inedible",
        "what a wretched and loathsome display",
        "i find this deeply offensive to my senses",
        "the spoiled garbage smells absolutely awful",
        "this revolting spectacle makes me gag",
        "i am horrified and disgusted in equal measure",
        "the slimy texture made me physically ill",
        "this foul stench is beyond description",
        "i am utterly revolted by this depravity",
        "the rancid smell permeates everything",
        "this sickening display turns my stomach",
        "i want to scrub myself clean after seeing that",
        "the grotesque appearance is too much to bear",
        "what a disgusting excuse for a human being",
        "i am repulsed by this vile contamination",
        "the noxious fumes are making me dizzy",
        "this is the most disgusting meal i have ever had",
        "i am sickened by the sheer filth around me",
        "the maggots and rot are absolutely repulsive",
        "this foulness offends every one of my senses",
        "i cannot stomach this nauseating presence",
        "the fetid swamp reeked of decay and death",
        "what a loathsome and contemptible action",
        "i am appalled by this grotesque exhibition",
        "the squalid conditions are beyond disgusting",
        "this repugnant odor clings to everything",
        "i feel contaminated just by being near this",
        "the vile substance made me retch uncontrollably",
        "this abhorrent behavior disgusts me to my core",
        "the slimy residue left me feeling unclean",
        "i am thoroughly disgusted by this entire affair",
        "the decaying matter emitted a sickening stench",
        "this revolting mess is a biohazard waiting to happen",
        "i find this absolutely stomach turning and foul",
        "the obnoxious filth is beyond my tolerance",
        "this repulsion i feel is visceral and real",
        "the nastiness of this situation is overwhelming",
        "i am utterly repelled by this sickening sight",
        "the squalor and grime are indescribably foul",
        "this noxious garbage heap reeks to high heaven",
        "i am sick to my stomach from this repugnant odor",
        "the foul taste lingered in my mouth for hours",
    ],
    'surprised': [
        "oh my god i did not expect that at all",
        "what a shocking turn of events this is",
        "i am completely stunned and speechless",
        "wow i never saw that coming in a million years",
        "this is the most surprising thing i have ever seen",
        "my jaw literally dropped when i heard the news",
        "i am absolutely floored by this revelation",
        "what an unexpected and incredible surprise",
        "i cannot believe my eyes this is unreal",
        "this caught me completely off guard",
        "i am astonished beyond words right now",
        "no way that is absolutely mind blowing",
        "the shock of this moment is overwhelming",
        "i am genuinely taken aback by what happened",
        "this revelation has left me utterly bewildered",
        "what a plot twist nobody could have predicted",
        "i am flabbergasted by this unexpected outcome",
        "this news came out of absolutely nowhere",
        "i never in my wildest dreams imagined this",
        "the surprise left me standing there speechless",
        "i am reeling from this shocking development",
        "what a breathtaking and unexpected moment",
        "this is so unexpected i need a moment to process",
        "i am dumbfounded by this incredible turn of events",
        "the gasp i let out could be heard across the room",
        "i am truly amazed by this wonderful surprise",
        "this left me absolutely thunderstruck and amazed",
        "i did a double take when i saw what happened",
        "the unexpectedness of it all is simply staggering",
        "my eyes widened in disbelief at the sight",
        "this startling revelation changes everything",
        "i am gobsmacked by this unforeseen development",
        "what a bolt from the blue this turned out to be",
        "i am completely bowled over by this surprise",
        "the shock value of this moment is off the charts",
        "this came as a total bombshell to everyone",
        "i am staggered by the magnitude of this surprise",
        "what an eye opening and unexpected experience",
        "this knocked me for six i was not prepared",
        "i am utterly amazed at how things unfolded",
        "the astonishment i feel is genuine and profound",
        "this curveball caught everyone by complete surprise",
        "i never anticipated such a dramatic outcome",
        "what a revelation this has been truly shocking",
        "i am agog at this breathtaking development",
        "the element of surprise here is unprecedented",
        "this unexpected gift left me teary eyed with joy",
        "i stood there paralyzed by sheer amazement",
        "what a bombshell announcement that was",
        "this electrifying surprise sent chills down my spine",
    ],
    'neutral': [
        "it is just another ordinary day nothing special",
        "i have no particular feelings about this matter",
        "the weather is mild and unremarkable today",
        "everything is going according to the usual routine",
        "i am simply observing without any strong emotions",
        "this is a standard procedure nothing exciting",
        "i acknowledge the situation without any reaction",
        "the facts are clear and straightforward enough",
        "it is what it is neither good nor bad",
        "i am maintaining a calm and balanced perspective",
        "the meeting was uneventful and predictable",
        "just going through the motions of daily life",
        "i have nothing noteworthy to report right now",
        "the situation remains unchanged and stable",
        "things are operating at a normal baseline level",
        "i am in a steady and composed state of mind",
        "the data shows no significant deviation",
        "i am approaching this with objective reasoning",
        "this is a typical example of the phenomenon",
        "nothing out of the ordinary is happening today",
        "i remain impartial and detached from the outcome",
        "the routine continues without interruption",
        "i am simply stating the facts as they are",
        "the conditions are average and perfectly normal",
        "i hold no strong opinion one way or the other",
        "this is business as usual nothing more",
        "i am functioning at my regular capacity",
        "the situation calls for practical assessment",
        "i observe without any emotional investment",
        "everything is in its proper place and order",
        "i maintain a neutral stance on this issue",
        "the report contains standard information only",
        "i am neither impressed nor disappointed by this",
        "this falls within the expected range of outcomes",
        "i approach this matter with logical detachment",
        "the day passed without any notable incidents",
        "i assess the circumstances with clear judgment",
        "the tone of the conversation was matter of fact",
        "i am in a state of emotional equilibrium",
        "this is simply a factual account of events",
        "i have a balanced view of the whole situation",
        "the process follows the established protocol",
        "i am composed and unruffled by recent events",
        "the metrics indicate stable performance overall",
        "i accept this outcome without any resistance",
        "the environment is quiet and undisturbed",
        "i am functioning on autopilot right now",
        "this is a routine check with nothing unusual",
        "i maintain a level headed approach to problems",
        "the atmosphere is calm and without tension",
        "i am not particularly moved either way by this",
        "the exchange was professional and courteous",
        "i find this to be an unremarkable development",
        "the status quo remains intact and unchallenged",
        "i am going about my business as usual",
        "the event transpired without any drama",
        "i view this through an objective lens only",
        "the presentation was informative but dry",
        "i am resting in a comfortable state of being",
        "this decision requires rational consideration",
    ],
}

print(f"Text samples per emotion:")
total = 0
for e, texts in emotion_texts.items():
    print(f"  {e}: {len(texts)} sentences")
    total += len(texts)
print(f"  TOTAL: {total}")

# Save texts
with open(os.path.join(DATA_DIR, 'real_texts.json'), 'w', encoding='utf-8') as f:
    json.dump(emotion_texts, f, ensure_ascii=False, indent=2)
print(f'Saved to data/real_texts.json')

# Also save as flat list
all_entries = []
for emotion, texts in emotion_texts.items():
    for text in texts:
        all_entries.append({"text": text, "label": emotion})
with open(os.path.join(DATA_DIR, 'text_corpus.json'), 'w', encoding='utf-8') as f:
    json.dump(all_entries, f, ensure_ascii=False)
print(f'Saved {len(all_entries)} entries to data/text_corpus.json')
print('[OK] High-quality text corpus ready!')
